title: Scrybe Docs
tagline: The other Scratch compiler
description: Scrybe is a text-based language implemented in Python that transpiles into a Scratch project.
domain: scrybelang.github.io
url: https://scrybelang.github.io
repository: ScrybeLang/Scrybe
github_username: Bituvo

aux_links:
  "Scrybe on GitHub":
    - "https://github.com/ScrybeLang/Scrybe"

theme: just-the-docs
highlighter: rouge

defaults:
  - scope:
      path: "assets"
    values:
      image: true

exclude:
  - vendor
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
